name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 15.164.30.174
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/SceneLens
            git pull origin main
            source .venv/bin/activate
            pip install -r backend/requirements.txt -q
            sudo systemctl restart scenelens
            sudo systemctl status scenelens --no-pager
